---
# dependencies
- include: dependencies.yml

# user
- include: user.yml

# database
- include: postgres.yml
  when: sentry_with_postgres

# sentry
- name: install sentry dependencies
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - python-setuptools
    - python-dev
    - python-pip

- name: create sentry directory
  file:
    path: "{{ sentry_home }}/.sentry"
    owner: "{{ sentry_user }}"
    group: "{{ sentry_user }}"
    mode: 0760
    state: directory
    recurse: yes

- name: copy config files
  template:
    src: "sentry.conf.py.j2"
    dest: "{{ sentry_home }}/.sentry/sentry.conf.py"
    owner: "{{ sentry_user }}"
    group: "{{ sentry_user }}"
    mode: 0600
  notify:
    - restart sentry

- name: install virtualenv
  pip:
    name: virtualenv

- name: install pexpect
  pip:
    name: pexpect
    virtualenv: "{{ sentry_home }}/env"

- name: install sentry
  pip:
    name: "{{ item }}"
    virtualenv: "{{ sentry_home }}/env"
  with_items:
    - "sentry[postgres]"
    - "git+https://github.com/dwaiter/django-bcrypt#egg=django-bcrypt"

- name: install sentry plugins
  pip:
    name: "{{ item }}"
    virtualenv: "{{ sentry_home }}/env"
  with_items: sentry_plugins

- name: correct folder permissions
  file:
    path: "{{ sentry_home }}/env"
    owner: "{{ sentry_user }}"
    group: "{{ sentry_user }}"
    recurse: yes

- name: migrate database
  shell: "su {{ sentry_user }} -c 'source {{ sentry_home }}/env/bin/activate && sentry --config={{ sentry_home }}/.sentry/sentry.conf.py upgrade'"

- name: copy superuser creation template
  template:
    src: "createsuperuser.py.j2"
    dest: "{{ sentry_home }}/temp.py"
    owner: "{{ sentry_user }}"
    group: "{{ sentry_user }}"

- name: create sentry super user
  shell: "su {{ sentry_user }} -c 'source {{ sentry_home }}/env/bin/activate && python {{ sentry_home }}/temp.py'"

- name: remove superuser creation template
  file:
    path: "{{ sentry_home }}/temp.py"
    state: absent

# nginx
- include: nginx.yml
  when: sentry_with_nginx

# supervisor
- include: supervisor.yml
  when: sentry_with_supervisor
