---
- name: install postgres packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - postgresql
    - postgresql-contrib

- service:
    name: postgresql
    state: started

- name: setup database
  sudo_user: postgres
  postgresql_db:
    db: "{{ sentry_db }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: grant access for database to user
  sudo_user: postgres
  postgresql_user:
    db: "{{ sentry_db }}"
    user: "{{ sentry_db_user }}"
    password: "{{ sentry_db_password }}"
    role_attr_flags: "CREATEDB,SUPERUSER"
    state: present
