---
- name: add sentry user
  user:
    name: "{{ sentry_user }}"
    state: "present"
    home: "{{ sentry_home }}"
    shell: "/bin/bash"

- name: chown sentry sentry_user directory
  file:
    path: "{{ sentry_home }}"
    owner: "{{ sentry_user }}"
    state: "directory"